fenndragon/HardLight

Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/energy.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/hitscan.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/pistol.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/rifle.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Rifles/rifles_assault.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml

Refactored all projectiles to have damage more in line with normal gameplay experience, undoing the previous damage overhaul in general
New combat was entirely stun meta centric and did not reward players for engaging in actual conflict, this will allow people to actually feasibly win firefights without going through several magazines of lethal rounds on slightly armoured targets.
Changes to .yml files in the projectiles directory, refactor of damage values
Spawn in dev env
Spawn gun
Shoot urist
Do not take nearly entire magazine to crit urist while wearing basic armour
**Changelog**
- tweak: Weapon damage overhaul

Weapon overhaul damage reversion

---

Resources/Prototypes/Maps/core.yml

it freaking loads after changing the name and grid ID to match

finally, a working build

---

Resources/Prototypes/Maps/core.yml

see design document checklists for full changes to Core
flipped cargo depot sale values to high
enabled Valet

updates to Core, other misc mapping

---

Resources/Prototypes/Maps/core.yml

Per Corvid
"Most of the changes involved the docking arms. I set every console and vending machine to unanchorable. Changed the camera types from service to general. Went through all the main hallways of the main station and added more lights. Fixed a bunch of nitpicky shit and did some changes in engineering. Oh
and I guess the biggest thing was setting up an RTG (renamed it to DMG) and have it producing 500kw to power the main docking arm."

updates to Core

---

Content.Shared/Standing/StandingStateSystem.cs

fixed standing speed not resetting

---

Resources/Prototypes/_NF/Guidebook/rules.yml

added prototypes for all rule .xml files

fixed rules

---

Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_silicons.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_rogue_ai.yml

Added back the silicon ability to res, gave them the bluespace drops again and re-added the circuits albeit at a reduced rate for most
I liked how they were before and I love a challenge. The t4 bots still drop the flatpacks/circuitboards at full drop rate because they're crazy hard to beat in a fight
**Changelog**

MACHINE TURN BACK NOW

---

Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
Resources/Prototypes/Roles/Jobs/Civilian/librarian.yml
Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml
Resources/Prototypes/Roles/Jobs/Wildcards/psychologist.yml
Resources/Prototypes/Roles/Jobs/Wildcards/zookeeper.yml

commenting out access groups, for now

removing access groups

---

Resources/Maps/_HL/Shuttles/ColSec/mosquito.yml
Resources/Maps/_HL/Shuttles/ColSec/stalker.yml
Resources/Prototypes/_HL/Shipyard/ColSec/mosquito.yml
Resources/Prototypes/_HL/Shipyard/ColSec/stalker.yml

Re-adds the Mosquito and Stalker, with fixes

Re-adds mosquito and stalker with fixes

---

Resources/Prototypes/Guidebook/rules.yml
Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_silicons.yml

this was the wrong ID

---

Resources/Prototypes/_NF/Catalog/Fills/Items/weapon_cases_expedition.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/base_bullets.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/pistol.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/rifle.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Pistols/base_pistol.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/SMGs/base_smg.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/expedition_guns.yml

Went through and tweaked all the damage values to be more familiar, tweaked the atredies and c-20 a bit, made the jackdaw a t5 exped drop again, and added some caseless boxes to the cobra and jackdaw weapon cases
**Changelog**

GUN CHANGES THE FOURTH

---

Content.Shared/Access/Components/IdCardConsoleComponent.cs
Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Roles/Jobs/departments.yml

Uncommented additional accesses on ID computer
Give station roles their unique accesses back
**Changelog**

Id comp pass

---

Resources/Prototypes/_NF/Entities/Structures/Machines/vending_machines.yml

change vending machines to Merc only

vending machine access

---

Resources/Maps/core.yml
Resources/Prototypes/_HL/GameRules/events.yml

Update events.yml.
Hopefully will make it so we get only one of each mob spawn every 60 minutes.
I hope this fixes things, I really do...

Various Mapping/Game Fixes (Core, Vent Spawns)

---

Content.Server/GameTicking/GameTicker.RoundFlow.cs
Content.Server/Shuttles/Systems/ArrivalsSystem.cs

round restart

---

Resources/Maps/Misc/terminal.yml

Please, for the love of all that is holy, work ><
Added Cryogenic Sleep Units.
Added ATMs.
Added Borg Recharging Units.
Added Pacifist Zone Marker.
Added Portal Gateway.
Fixed missing wall.
Fixed errant tiles 200 tiles south of ColComm.
Fixed Atmos, again, hopefully.
Removed Arrivals Dock.

Update terminal.yml, again

---

Resources/Maps/colcomm.yml

ColComm Update

---

Resources/Prototypes/Catalog/Fills/Lockers/security.yml

Tweak pass on core.yml, covering aesthetics in the docking ring, replacing guns with incorrect calibres with correct ones, etc
https://i.imgur.com/kV6A5G0.png
https://i.imgur.com/ymGRlV9.png
https://i.imgur.com/wbjldEr.png
https://i.imgur.com/rxJ5QYH.png 
https://i.imgur.com/OKZaPw1.png
**Changelog**
:cl:
- fix: Guns in security now have the correct calibres
- change: The Paramedic's office now starts with a paramedic hoverbike
- tweak: Tweaked the aesthetics and layout of parts of the station, primarily in and around the docking wing, and added a new room to maintenance
- add: Added a radar console to the bridge

core.yml tweaks and fixes

---

Resources/Prototypes/Species/slime.yml

Minor note: some tails have odd transparency because of layering and transparency.

Lets slimepeople have animal ears and tails.

---

Resources/Prototypes/_NF/Entities/Structures/Machines/lathe.yml

Fix lathes missing OreSiloClient component

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Turrets/turrets_base.yml

HOTFIX: Stop AI turrets from causing flickering lights (#38212)

---

Resources/Prototypes/Entities/Mobs/NPCs/miscellaneous.yml

copied drdino down to his original parent file.
**Changelog**

Fix DrDino8's yaml parent (test for Fenn's coding class =])

---

Resources/Prototypes/_CD/Entities/Objects/Misc/contraband.yml

I would never be stupid and leave in a dupe exploit

exploit and balance fixes

---

Resources/Maps/_HL/Shuttles/peacekeeper.yml
Resources/Prototypes/_HL/Shipyard/Expedition/peacekeeper.yml

Adds the SCC Peacekeeper private security shuttle, by Alkashy

Adds the SCC Peacekeeper by Alkashy

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml

Added OreSiloClient Component to Cutter Machine & Uniform Printer
Convenience & i think builders and players who uses these machines will appreciate not needing to seperate their materials like how Mercfab used to be
Added "-Type : OreSiloClient" at the end of Cutter Machine & Uniform Printer Codes
-Establish a Material Silo, Add any materials in it,
-Use the machines of either Cutter or Uniform Printer
-Check if there is a material linked in the UI
**Changelog**

Added OreSiloClient component to Cutter Machine & Uniform Printer

---

Resources/Prototypes/Research/industrial.yml

Fultons and Fulton Beacons can now actually be unlocked and made per the earlier PR.  Requires Advanced Tools research and a protolathe.  I don't know how to make it work on the lathe it's supposed to, but it's something.
**Changelog**

Fulton Fix (Sort Of)

---

Resources/Prototypes/_Goobstation/Entities/Clothing/Head/hardsuit-helmets.yml
Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml

The stealth hardsuit no longer spams errors when worn

---

Resources/Prototypes/_NF/Entities/Materials/ore.yml
Resources/Prototypes/_NF/Recipes/Lathes/Packs/scrap.yml
Resources/Prototypes/_NF/Recipes/Lathes/materials.yml

Lets you produce tech disks from scrap.  Roughly balanced according to relative speso value of scrap and research disks as defined by Frontier.
I added a recipe to the Scrap Processor to print tech disks.  It has a more or less equal chance of making a 1K, 5K, and 10K disk.
I also added the spawner that makes it work.
This lets people more easily progress through the tech tree without relying entirely on unpredictably explosive artifacts or station-threatening anomalies at the cost of so, so, so much time mining.
Add scrap to scrap processor.
Print tech disks.
Tada!
**Changelog**

Scrap Tech Addition

---

Content.Client/Shuttles/Save/ShipFileManagementSystem.cs
Content.Client/_NF/Shipyard/UI/ShipyardConsoleMenu.xaml
Content.Client/_NF/Shipyard/UI/ShipyardConsoleMenu.xaml.cs
Content.Server/Shuttles/ShipSerializationSystem.cs
Content.Server/_NF/Shipyard/Systems/ShipyardSystem.Consoles.cs
Content.Server/_NF/Shipyard/Systems/ShipyardSystem.cs
Content.Shared/Shuttles/Save/ShipConvertedToSecureFormatMessage.cs
Content.Shared/_NF/CCVar/NFCCVars.cs
Resources/Locale/en-US/_NF/shipyard/shipyard-console-component.ftl

Fixes loaded ship selling
loading multiple times
checksum
adds feedback when loading without a ID as well as audio feedback in general
made checksum validation a cvar that can be disabled, in case it breaks (ShipyardChecksumValidation)
added forcible conversion to the new checksum method
and now i sleep

Ship saving hotfixes

---

ADMIN_SHIP_COMMANDS.md
Content.Client/Shuttles/Save/ShipFileManagementSystem.cs
Content.Client/_NF/Shipyard/BUI/ShipyardConsoleBoundUserInterface.cs
Content.Server/Administration/Commands/ShipSaveAdminCommands.cs
Content.Server/Entry/EntryPoint.cs
Content.Server/IoC/ServerContentIoC.cs
Content.Server/Shuttles/Save/ShipSaveSystem.cs
Content.Server/Shuttles/ServerIdentityService.cs
Content.Server/Shuttles/ShipSerializationSystem.cs
Content.Server/_NF/Shipyard/Systems/ShipyardSystem.Consoles.cs
Content.Server/_NF/Shipyard/Systems/ShipyardSystem.cs
Content.Shared/_NF/Shuttles/Save/ShipGridData.cs
Content.Shared/_NF/Shuttles/Save/ShuttleSaveMessages.cs

Blacklisting doesn't work rn, we'll get there

Ship Saving refinements

---

Content.Client/Shuttles/Save/ShipFileManagementSystem.cs
Content.Server/Shuttles/ShipSerializationSystem.cs

Ship saving optimization

---

Resources/Prototypes/Entities/Structures/Machines/reagent_grinder.yml

Makes the Industrial Reagent Grinder have a storage capacity equal to that of a bluespace beaker so it's no longer completely outclassed by its smaller version.
**Changelog**

Industrial Reagent Grinder Tweak

---

Resources/Prototypes/_NF/Entities/Clothing/Belt/belts_crossbow_quiver.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Crossbow/crossbow.yml

This update makes Crossbows work like Bows, with an 8-shot 'magazine' (to compensate for the lower damage of bolts vs. bodkin and broadhead arrows, which have 2.5x the base damage) and quivers holding 24 bolts and functioning like ammunition boxes.  Quiver visuals don't work yet, I don't know why.
**Changelog**

Crossbow Buff

---

Resources/Maps/_HL/Shuttles/apollo.yml
Resources/Prototypes/_HL/Shipyard/apollo.yml

A medium, armoured medevac and search and rescue shuttle, with a frontal boarding ramp. Built by BlueNexa, HammeredMantis and Rookknight.

Adds the THI Apollo

---

Resources/Prototypes/_HL/Shipyard/apollo.yml

Better apollo description

---

Resources/Prototypes/_HL/Shipyard/apollo.yml

Final Apollo shuttle description

---

Content.Server/EntityEffects/Effects/RestoreBloodReagent.cs

[DO NOT MERGE] Linter fixes

---

Content.IntegrationTests/Tests/_NF/Shipyard/ShipyardGridSaveTest.cs
Content.Server/Atmos/Components/GridAtmosphereComponent.cs
Content.Server/Shuttles/Save/ShipSaveSystem.cs
Content.Server/Shuttles/ShipSerializationSystem.cs
Content.Server/_NF/Shipyard/Systems/ShipyardGridSaveSystem.cs.backup
Content.Server/_NF/Shipyard/Systems/ShipyardSystem.cs

potential fixes for ship saving, items no longer serialized for now

ship saving fix

---

Resources/Prototypes/_HL/Shipyard/Avali/Nest.yml

Price adjustment for the nest

---

Resources/Prototypes/_HL/Entities/Clothing/Back/spiderblades.yml

Quick spider blade tweaks

---

Resources/Locale/en-US/_HL/store/SecurityVending.ftl
Resources/Prototypes/_HL/Catalog/uplink_catalog.yml
Resources/Prototypes/_HL/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Resources/Prototypes/_HL/Entities/Structures/Machines/vending_machines.yml
Resources/Prototypes/_Mono/Catalogs/security_uplink_catalog.yml
Resources/Prototypes/_Mono/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
Resources/Prototypes/_NF/Catalog/security_uplink_catalog.yml
Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/hardsuits.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml

Unlocks the nsfd uplink
Sec kinda of sucks not going to lie
Spawn it in and try it 
**Changelog**
:cl:
- tweak: Inventory of the security Vending machine

Security Vending UPDATE 

---

Resources/Prototypes/Nyanotrasen/Species/felinid.yml
Resources/Prototypes/Nyanotrasen/Species/oni.yml
Resources/Prototypes/Species/arachnid.yml
Resources/Prototypes/Species/diona.yml
Resources/Prototypes/Species/human.yml
Resources/Prototypes/Species/moth.yml
Resources/Prototypes/Species/reptilian.yml
Resources/Prototypes/Species/slime.yml
Resources/Prototypes/Species/vox.yml
Resources/Prototypes/_DV/Species/feroxi.yml
Resources/Prototypes/_DV/Species/harpy.yml
Resources/Prototypes/_DV/Species/rodentia.yml
Resources/Prototypes/_DV/Species/vulpkanin.yml
Resources/Prototypes/_EinsteinEngines/Species/ipc.yml
Resources/Prototypes/_NF/Species/goblin.yml
Resources/Prototypes/_NF/Species/sheleg.yml

Fix the species and normalize the marking amounts to 8 chest, 8 leg, 8 arm

---

Resources/Prototypes/_HL/Entities/Objects/Nanotrasen/clothing.yml

Updated high pressure multiplier and clothing speed modifiers. Removed temperature and zombification resistance attributes.

NT hardsuit parity

---

Resources/Prototypes/_NF/Body/Organs/synthetic_organs.yml

copied over code from Resources/Prototypes/Body/Organs/human.yml  to  Resources\Prototypes\_NF\Body\Organs\synthetic_organs.yml  in order to make the organs work with the Shitmed surgery system
**Changelog**

Added Shitmed Compatibility for NF synthetic organs

---

Content.Server/_HL/RoundPersistence/Systems/RoundPersistenceSystem.cs

Persistence Test

---

Resources/Prototypes/Entities/Structures/Storage/Closets/big_boxes.yml

patching miscode in the stealthbox code, resulting in it being indestructable

making stealth boxes breakable

---

Resources/Prototypes/Nyanotrasen/Entities/Markers/Spawners/jobs.yml

mapping fix for core, mantis and brig med spawners

---

Resources/Prototypes/Nyanotrasen/Recipes/Construction/Graphs/structures/glimmerdevices.yml

Make drains actually craftable

---

Resources/Prototypes/Species/moth.yml

Added 1 marking count for moth hair and moth facial hair.
This fixes why moth hairs were not working.
[Species/moth.yml](https://github.com/fenndragon/HardLight/compare/master...AryaRaiin:AryaHardLight:moth-marking-count?expand=1#diff-abdfe0be070f798b76f6fa6c83a7418c820744cfadd22a38c8d4f03ff9bc687b) hair and facial hair markings increased 0 -> 1
Load up to game and go lobby, pick a moth in character customization and select a hair!
No breaking changes!
:cl:
- fix: Increased moth hair and facial hair markings from 0 to 1 so hairs can be used.

Increased moth hair and facial hair markings

---

Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
Resources/Prototypes/Loadouts/Jobs/Security/security_officer.yml
Resources/Prototypes/Loadouts/role_loadouts.yml

various bug fixes

---

Content.Client/_NF/Shipyard/BUI/ShipyardConsoleBoundUserInterface.cs
Content.Server/Diagnostics/EntitySpawnProfilerSystem.cs
Content.Server/Light/EntitySystems/PoweredLightSystem.cs
Content.Server/Shuttles/Save/ShipSaveSystem.cs
Content.Server/Shuttles/ShipSerializationSystem.cs
Content.Server/Shuttles/Systems/DockingSystem.cs
Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
Content.Server/_NF/Shipyard/Systems/ShipyardGridSaveSystem.cs
Content.Server/_NF/Shipyard/Systems/ShipyardSystem.Consoles.cs
Content.Server/_NF/Shipyard/Systems/ShipyardSystem.cs
Content.Shared/VendingMachines/VendingMachineComponent.cs
Resources/Locale/en-US/atmos/air-alarm-ui.ftl
Resources/Locale/en-US/damage/damage-popup-component.ftl
Resources/Locale/en-US/reagents/meta/medicine.ftl
Resources/Locale/en-US/temperature/entity-heater.ftl

this may potentially be the finalized version of ship saving prior to item cleanup and bluespace stash implementation

final shipsaving

---

Content.Server/_NF/Shipyard/Systems/ShipyardSystem.Consoles.cs
Content.Server/_NF/Shipyard/Systems/ShipyardSystem.cs

Packaged into a PR for easy reversal <3
Temporarily comments out the calls for clientside ship deletion while we work out stability issues

Temporarily comments out clientside ship file deletion

---

Resources/Prototypes/_HL/Shipyard/Shuttles/Antediluvian.yml

buy for 16k sell for 19k off the bat 
**Changelog**
:cl:
- fix: Fixed Antediluvian price

increase Antediluvian

---

Resources/Prototypes/_HL/Shipyard/Shuttles/Antediluvian.yml

Reverts fenndragon/HardLight#301
Still work to do

Revert "increase Antediluvian"

---

Resources/Locale/en-US/_HL/job/job-names.ftl
Resources/Prototypes/_HL/Admeme/AdminCharacterBundles/CommonItems/chemical_containers.yml
Resources/Prototypes/_HL/Admeme/AdminCharacterBundles/CommonItems/disposable_items.yml
Resources/Prototypes/_HL/Admeme/AdminCharacterBundles/CommonItems/extra_items.yml
Resources/Prototypes/_HL/Admeme/AdminCharacterBundles/CommonItems/micro_reactor_items.yml
Resources/Prototypes/_HL/Admeme/AdminCharacterBundles/arachne_cartel_elite.yml
Resources/Prototypes/_HL/Admeme/AdminCharacterBundles/marrik_bounty_hunter.yml
Resources/Prototypes/_HL/Admeme/AdminCharacterBundles/vulrik_thornepelt_colcom.yml
Resources/Prototypes/_HL/Admeme/AdminCharacterBundles/winter_gunslinger.yml

**Changelog**
- add: more secret admin character stuff

Custom character work (submission 2)

---

Resources/Maps/_HL/Shuttles/Expedition/mayflowerII.yml
Resources/Prototypes/_HL/Shipyard/Expedition/mayflowerII.yml

Mayflower Mk II revised 
